name: Deploy2 to server

#evento
on: 
  push:
    branches:
      - main

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      NAME: PruebaVariableDeEntorno #para que todos los steps accedan

    steps:
      - name: Inicial
        run: echo "Iniciando deploy $NAME" #directamente en el step

  second_jobs:   #ejecutate siempre y cuando el contexto de la referencia de github sea ...
    if: ${{ github.ref == 'refs/heads/main'}}   #un solo if a nivel job o a nivel step
    needs: first_jobs  #acepta lista tambien a todos los jobs necesarios
    runs-on: ubuntu-latest

    steps:
      - name: Inicial2
        run: echo "Iniciando deploy job 2 ${{ github.ref}}"