name: Deploy to server

#evento
on: 
  push:
    branches:
      - main

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Inicial
        run: echo "Iniciando deploy"

  second_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Inicial2
        run: echo "Iniciando deploy job 2"