name: "Deploy"

on:       #disparador, hara un push sobre la rama main
  push:   
    branches: ["main"]

jobs:
  deploy:   #cada job se debe ejecutar sobre un runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  #va a clonar el repositorio
      - run: python3 -m venv venv
      #- run: ruby main.rb
      - run: mkdir carpbackup
      - run: cd carpbackup
      - run: touch version.txt
      - run: ls
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "generar binario"
      - run: echo "publicar version"
  #send-notification:   correran en paralelo otros jobs
  #test-code: