name: Deploy to server

#evento
on: 
  push:
    branches:
      - main

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Inicial
        run: echo "Iniciando deploy"

  second_jobs:   #ejecutate siempre y cuando el contexto de la referencia de github sea ...
    if: ${{ github.ref == 'refs/heads/main'}}
    needs: first_jobs  #acepta lista tambien a todos los jobs necesarios
    runs-on: ubuntu-latest

    steps:
      - name: Inicial2
        run: echo "Iniciando deploy job 2"